### ISSUE TITLE
minecraft:click issue

### ISSUE THREAD

**Issue by SHXRKIEgg** [wisp-forest/owo-lib#10]
Hi, my players playing my Modpack have been having this issue, I'm just wondering if its related to your registering?
[Error.txt](https://github.com/gliscowo/owo-lib/files/7836304/Error.txt)
[Latest_log_of_disconection.log](https://github.com/gliscowo/owo-lib/files/7836305/Latest_log_of_disconection.log)

**Comment by SHXRKIEgg** [comment]
I think I have found the issue, The Wild Mod [FABRIC] says its an issue in their mod but I guess you can still check the error and see what you think.

**Comment by gliscowo** [comment]
I'll close this is as invalid for now as I don't see how this could related to owo, but feel free to reopen it should more suspicion arise
