### ISSUE TITLE
Item render issue

### ISSUE THREAD

**Issue by fungoza** [wisp-forest/owo-lib#105]
No item is rendered in an ItemComponent
(Reported in owo-lib because developer can see item models)
mods:
fabric-api-0.75.1+1.19.3.jar
owo-lib-0.10.2+1.19.3.jar
fzmm-mc1.19.3-0.1.2.jar (https://cdn.discordapp.com/attachments/1015884459654008902/1079853939299713214/fzmm-mc1.19.3-0.1.2.jar)
(my screenshots)
![image](https://user-images.githubusercontent.com/68079109/221694581-2067b78d-f9ac-4a73-b522-1ab60a8e7ae6.png)
![image](https://user-images.githubusercontent.com/68079109/221696178-6696c5b2-b95a-4926-8c8c-08b8133da687.png)

(developer screenshots)
![image](https://user-images.githubusercontent.com/68079109/221694673-e4c70a39-115b-456f-a69f-82ddd60240d5.png)
![image](https://user-images.githubusercontent.com/68079109/221696109-de9ccc86-1e95-40fa-b96c-7ade8c8ddc67.png)

manual crash for hardware information:
[crash-2023-02-28_01.56.45-client.txt](https://github.com/wisp-forest/owo-lib/files/10844689/crash-2023-02-28_01.56.45-client.txt)

**Comment by fungoza** [comment]
![image](https://user-images.githubusercontent.com/68079109/221828654-8d2fc036-5618-4ed6-818f-58eb7cb8590c.png)
Numismatic Overhaul (numismatic-overhaul-0.2.8+1.19.3.jar) item render don't work too
[latest.log](https://github.com/wisp-forest/owo-lib/files/10849248/latest.log)
Maybe this? `[14:25:44] [Render thread/WARN]: @ModifyVariable(@At("INVOKE")) Shift.BY=2 on owo.mixins.json:ui.ItemRendererMixin from mod owo::localvar$zne000$owo$replaceMatrixStackIfCached exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.`

**Comment by gliscowo** [comment]
Where exactly did you get this build of owo from? As far as I can tell this mixin only exists in an unmerged PR - so how exactly did it get into your game?

I would imagine that something about that mixin is causing this to break, but since that PR was never merged I fail to understand how it got into your game 🤔

**Comment by fungoza** [comment]
Oh, I installed version from Action tab in github (file date 6(7) February)
As I understand, this is error of #94

**Comment by gliscowo** [comment]
Have you tested with an official release?

**Comment by fungoza** [comment]
> Have you tested with an official release?

Yes, it works normal

**Comment by gliscowo** [comment]
Alright, thanks. I'll be closing this issue then - @Dragon-Seeker will have to investigate #94 to see what causes this

Cheers
