### ISSUE TITLE
owo-ui: Data-driven text box trims preset text to the default limit, even when a max-length is set

### ISSUE THREAD

**Issue by anonymous123-code** [wisp-forest/owo-lib#110]
For example the text of
```xml
<text-box>
    <max-length>300</max-length>
    <text>This is an example text longer than 32 chars, which is the default limit</text>
</text-box>
```
will get trimmed to `This is an example text longer t`

This happens because at https://github.com/wisp-forest/owo-lib/blob/30aa4c11a6fad97ca76afbd274d525fd29b09802/src/main/java/io/wispforest/owo/ui/component/TextBoxComponent.java#L68-L71

the text is set before the maximum length and the text setter trims the text if it is to long.

**Comment by gliscowo** [comment]
Thanks for reporting, this has been fixed in [0.10.3](https://modrinth.com/mod/owo-lib/version/gmwB5dLB)
