### ISSUE TITLE
[owo-ui] The second layer of the skins is not rendered correctly if it has transparency in EntityComponent

### ISSUE THREAD

**Issue by Zailer43** [wisp-forest/owo-lib#114]
## Attachments where the error can be seen
In these videos I am using other mods but it is reproducible being only with fabric-api + owo-lib + an affected mod

### Isometric renders

https://user-images.githubusercontent.com/63565983/226073937-af2eca8b-4f72-492c-8421-08c04fa58d70.mp4

what the skins should look like:
![image](https://user-images.githubusercontent.com/63565983/226074009-f0133325-2469-4493-8211-07068d70db15.png)
![image](https://user-images.githubusercontent.com/63565983/226074015-593ca9a1-95bd-4a3c-a455-70279baa9692.png)
![image](https://user-images.githubusercontent.com/63565983/226074019-7e39f72f-0e8a-479e-8bf5-cd53d3be4e32.png)

### FZMM (heads are EntityComponent)

https://user-images.githubusercontent.com/63565983/226073947-a5cb631d-479a-4155-bfc5-83e4cd19f4c7.mp4

## Details

minecraft_version = 1.19.3
owo_version = 0.10.3+1.19.3
fabric-api = 0.76.0+1.19.3
isometric-renders = 0.4.4+1.19.3
fzmm = mc1.19.3-0.2.1

**Comment by gliscowo** [comment]
While I have been able to reproduce and fix the problem in Isometric Renders (which does not use owo-ui for rendering content, only the controls), I failed to trigger it using an EntityComponent. Mind you that I've been conducting my testing with FZMM on 1.20 where the issue appears to have been fixed (presumably by the recent rendering refactors)

If you can confirm that the problem appears solved for owo's purposes, I'll go ahead and close this

**Comment by Zailer43** [comment]
sorry for taking so long to reply, yes, the bug seems to be solved in the latest versions
