### ISSUE TITLE
owo-lib does not work on quilt

### ISSUE THREAD

**Issue by jucogjucogi** [wisp-forest/owo-lib#116]
owo-lib does not work on quilt. 
when i launch mc with owo-lib and quilt, this happens:
![изображение](https://user-images.githubusercontent.com/113132803/227462286-2f781b4c-df37-4702-8b7a-12d3504faba6.png)
modrinth page says that both quilt and fabric supported, but i updated quilt to latest version and it still doesn't launch.
ask for logs if needed
latest qfapi ver. is installed

**Comment by BasiqueEvangelist** [comment]
Guess QFAPI hasn't updated to the newest Fabric API then
I don't know what we can really do about this, as we do use stuff from the newest FAPI (and QFAPI will probably merge in upstream anyways so)

**Comment by jucogjucogi** [comment]
ok, thx
