### ISSUE TITLE
Incompatible with Stendhal (Quilt 1.19.4)

### ISSUE THREAD

**Issue by rbits0** [wisp-forest/owo-lib#117]
When I use Stendhal and owo-lib together, the game gets to the Mojang screen and then crashes. The only mods I have installed are Stendhal, owo-lib, and QFAPI.
[latest.log](https://github.com/wisp-forest/owo-lib/files/11086122/latest.log)

Minecraft 1.19.4
Quilt 0.18.6
owo-lib 0.10.3+1.19.4
Stendhal 1.3.6-1.19.4
Quilted Fabric API 6.0.0-beta.2

**Comment by ianm1647** [comment]
i get the same crash

**Comment by gliscowo** [comment]
Essentially also a duplicate of the now-fixed #120
