### ISSUE TITLE
I can't even start the game because of an "incompatible mod set" that I have ABSOLUTELY no clue how to resolve

### ISSUE THREAD

**Issue by Devintrainer** [wisp-forest/owo-lib#118]
> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Replace mod 'oωo' (owo) 0.8.5+1.19, mod 'oωo-sentinel' (owo-sentinel) 0.8.5+1.19 and mod 'oωo-sentinel' (owo-sentinel) 0.9.3+1.19 with mod 'oωo' (owo), version 0.9.3 or later.
> Unmet dependency listing:
> 	 - Mod 'Mythic Metals' (mythicmetals) 0.17.3+1.19.2 requires version 0.9.3 or later of mod 'oωo' (owo), which can't be loaded due to other constraints!
> 	 - Mod 'Mythic Metals Decorations' (mythicmetals_decorations) 0.5.2+1.19.2 requires version 0.9.3 or later of mod 'oωo' (owo), which can't be loaded due to other constraints!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Disabling Mythic Metals does allow the game to run properly, but I want to use that mod still. What I have no idea about is how to make the game run properly WITH it enabled.

**Comment by Dragon-Seeker** [comment]
Have you tried updating the version of owo that is within your modpack? Update such mod to 0.9.3 version here: https://www.curseforge.com/minecraft/mc-mods/owo-lib/files/4152949

**Comment by Devintrainer** [comment]
That worked. But now I have encountered a new problem. I can't join any worlds because it disconnects me, even though I am in single player! And since I already have this thread open and I have even less of a clue as to why this new bug is happening, why not reuse it?

[latest.log](https://github.com/wisp-forest/owo-lib/files/11103609/latest.log)

**Comment by Noaaan** [comment]
From reading you log it seems something bad is happening with [Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric). I suggest asking them for further support.

**Comment by gliscowo** [comment]
Given that this issue is no longer related to owo, I'll go ahead and close it
Cheers
