### ISSUE TITLE
Incompatibility/crash with Blur 3.0.0

### ISSUE THREAD

**Issue by Auzathoth** [wisp-forest/owo-lib#120]
I'm getting a crash after the "joining world" message, on both single and mult-player, when running both owo & blur. There's also a "Resource reload failed" message when on the main menu.

owo 0.10.3+1.19.4
blur 3.0.0
Minecraft 1.19.4
Fabric Loader 0.14.18

[latest.log](https://github.com/wisp-forest/owo-lib/files/11104194/latest.log)

[crash-2023-03-29_19.19.40-client.txt](https://github.com/wisp-forest/owo-lib/files/11104207/crash-2023-03-29_19.19.40-client.txt)

**Comment by gliscowo** [comment]
This problem is caused the Satin library Blur uses. It has already been fixed on their development branch, although that fix has not yet been released into production - there's nothing we can do right now but wait

Cheers

**Comment by Auzathoth** [comment]
Is this always an issue with the underlying library? I've found a similar crash with Stendhal, which is using libgui:

> Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: libgui:libgui:shaders/core/tiled_rectangle.json

But only under Quilt API. Under Fabric API the same crash doesn't happen...

**Comment by gliscowo** [comment]
This has now been fixed on owo's side in [0.10.4](https://modrinth.com/mod/owo-lib/version/T8DsELMD)
Cheers
