### ISSUE TITLE
Add README screenshots

### ISSUE THREAD

**Issue by FazziCLAY** [wisp-forest/owo-lib#125]

**Comment by gliscowo** [comment]
This issue is in no way clear enough for us to have any concrete idea of what you're asking for. You'll need to be more specific if you like us to actually act on whatever it is you plan to propose

**Comment by FazziCLAY** [comment]
> [owo-ui](https://docs.wispforest.io/owo/ui/), a fully-featured declarative UI library for building dynamic, beautiful screens with blazingly fast development times

You need to add screenshots of the game, where the capabilities in terms of the interface will be demonstrated
