### ISSUE TITLE
Searching in config without matches crashes the game (1.19)

### ISSUE THREAD

**Issue by thehaffk** [wisp-forest/owo-lib#127]
I do not own this screencast, it is from [one](https://t.me/TheMeko) of my mod users

I think i can make a PR to fix this, but i don't have much time, srry

Logs with exception
https://mclo.gs/1Oh4D1R

Caused by: java.lang.ArithmeticException: / by zero 144 | at io.wispforest.owo.config.ui.ConfigScreen.lambda$build$4(ConfigScreen.java:186) ~[owo-lib-0.9.3+1.19.jar:?]

![image](https://user-images.githubusercontent.com/73640655/235696360-39086cee-4a3f-4eb4-ad80-0d94c5c3a498.png)

Video
https://user-images.githubusercontent.com/73640655/235694147-c61c146f-b872-489f-beb5-ddcf3a5e889d.mp4

**Comment by thehaffk** [comment]
Not searching actually, but double pressing enter key

**Comment by gliscowo** [comment]
This issues was fixed months ago (in a5c712e). Inconveniently, it hasn't made it into any public releases for 1.19.

While we understand that this bug can be potentially annoying, it is by no means game-breaking or even very severe - searching twice with an empty query is something that should not happen very often, if ever. Given this, and the fact that our 1.19 support cycle has ended a long time ago, we won't release a new build with the fix

Cheers
