### ISSUE TITLE
handshake failure

### ISSUE THREAD

**Issue by Saiko125** [wisp-forest/owo-lib#134]
![image](https://github.com/wisp-forest/owo-lib/assets/86660217/5e1d47e8-c5c5-464c-ba2b-07391a38242d)

I've been trying to join any server while I have owo lib in my mods and this started happening for like 2 days now 

issue mostly happened at the time when I updated fabric and fabric API on 1.19.4

is there any guide or help how to fix this?

**Comment by Noaaan** [comment]
A handshake failure like this indicates the server you are connecting to is, well, invalid. This is most often due to mismatching mods between your client and the server.

The fact you have owo-lib in your mods, and that handshake is enabled, means that one of your mods on the client **requires it to be present on the server too.**

If you are the server host, and you believe this is not the case, make sure you are not being blocked by a proxy like Velocity: https://docs.wispforest.io/faq/#i-get-disconnected-due-to-an-oo-handshake-failure-when-trying-to-join-a-server

**Comment by Saiko125** [comment]
I've been playing on servers that are valid and still running
just can't connect to them when I see this message pop out 

even when joining my local server it says the same thing and just disconnects me 

I would know how to change the dependency that I need to have "EXACT" mod set as servers or not have mods at all even if servers do not have mods I can't join them which is annoying me

**Comment by gliscowo** [comment]
Well, as a first step, what mods do you have on your client?

**Comment by Saiko125** [comment]
well this is weird that before it was ok but since I updated fabric and fabric API it all just gave me handshake failure

but mods I have 
![image](https://github.com/wisp-forest/owo-lib/assets/86660217/3a636485-d9a4-4203-a246-37bb9f39aef4)
![image](https://github.com/wisp-forest/owo-lib/assets/86660217/ef2d5931-d270-4735-b8fc-f2d42b264227)

**Comment by Saiko125** [comment]
previously they just allowed me to join any server but now they doesn't so I don't understand what's happening

**Comment by gliscowo** [comment]
To be quite honest, I can't exactly spot any mods in this list which would require handshake - I'm however also of course not intimately with every mod that has ever used owo networking. Generally, handshaking exists to protect you from joining incompatible servers - under which vanilla servers certainly fall when using this modlist. 

If you like to do it anyways, you can [supply the respective Java flag to completely disable handshaking on your client](https://docs.wispforest.io/owo/system-properties/#-dowohandshakedisable-truefalse). Do note however, that this will also prevent you from joining servers with a compatible mod set as they will expect your client to participate in the handshaking process

**Comment by Saiko125** [comment]
I can provide log if that could help more with the issue

**Comment by gliscowo** [comment]
It would certainly be worth a shot

**Comment by Saiko125** [comment]
[latest.log](https://github.com/wisp-forest/owo-lib/files/11645503/latest.log)

this hopefully should help identiy what mod does that 

if not then well I would have to go thru painful binary-split method of finding what's wrong and what mod does that

**Comment by Saiko125** [comment]
ok hello again sorry that this issue was pointless but I found the problem and it was things mod that caused the handshake failure

I hope that you have great day nonetheless and sorry for making the issue in here because of this
