### ISSUE TITLE
@Config generating .class files but not .java files

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [wisp-forest/owo-lib#135]
Hi.

I'm trying out owo-lib for the first time, so please excuse me if I've made a dumb mistake, but I have followed [this guide](https://docs.wispforest.io/owo/config/getting-started/) up until the part where you have to actually reference the generated config class. I have built the mod, as the guide said to do, but the generated class only exists in the built jars output by gradle, not in my source code. As such, I cannot reference it, causing a compilation error.

I am using owo version `0.10.6+1.19.4`.

**Comment by gliscowo** [comment]
Are you using IntelliJ to build your mod? If so, it is quite possible you need to run the game once before Idea will recognize the generated sources - it can be quite fiddly sometimes. 

To do this, you'll of course have to temporarily remove all potential references to your config class before running - after running it should show up.

Let me know if this helps
Cheers

**Comment by ThatBlockyPenguin** [comment]
Thanks for the quick reply!
I'm using Eclipse 2023-03

**Comment by gliscowo** [comment]
Hmmm, in that case I'm sorry to say that a good Googling session may be your best option. Neither me or anyone else on our team has ever used Eclipse for building mods.

If you like, I can also recommend joining [our Discord server ](https://discord.gg/xrwHKktV2d) where we can more easily provide support

**Comment by ThatBlockyPenguin** [comment]
Hmm alright, well thanks for trying!
If Google doesn't find me the answer, expect to see me in the Discord server soon :)
When I find the solution, would you like me to drop a pull request on the docs repository for other Eclipse users to follow?

**Comment by gliscowo** [comment]
If that's something you're open to do, we'd certainly welcome the contribution!

Hope you get your problem solved
Cheers

**Comment by ThatBlockyPenguin** [comment]
Of course! Happy to help :)
I think I've figured it out now, although Eclipse doesn't make it easy.

**Comment by ThatBlockyPenguin** [comment]
PR created https://github.com/wisp-forest/docs/pull/6 :)
