### ISSUE TITLE
[1.19.3] owo-lib constantly making the game reload

### ISSUE THREAD

**Issue by HoneyBadger1337** [wisp-forest/owo-lib#144]
When using owolib Minecraft keeps refreshing like one has tried to reload a resourcepack, but it will loop again and again immediately, i've isolated it with the only other mod being Sodium (otherwise my game wasn't letting me load) only and **if i unload owolib the issue will stop**

Video showing issue:
https://www.youtube.com/watch?v=D_Dj50BZz1o&feature=youtu.be

Included my latest.log file if it helps
[latest.log](https://github.com/wisp-forest/owo-lib/files/12002257/latest.log)

**Comment by Noaaan** [comment]
Seems related to https://github.com/wisp-forest/owo-lib/issues/82, you can try downgrading owo-lib to mitigate the issue.

**Comment by HoneyBadger1337** [comment]
Ah yep that workaround works, thanks Noaaan 👍
