### ISSUE TITLE
Using item groups makes the vanilla creative scrollbar dissappear on Quilt

### ISSUE THREAD

**Issue by sleepingdragoninn** [wisp-forest/owo-lib#149]
![image](https://github.com/wisp-forest/owo-lib/assets/55819817/47831095-d21e-449d-ae59-d242e76403ef)
![javaw_b1RE7v6uPV](https://github.com/wisp-forest/owo-lib/assets/55819817/b4ac7ef5-23ed-40fe-afca-dc0400080031)

The bar inside the custom groups is visible, but the bar in the regular tabs is completely invisible. it still works, it just doesn't display.

Tested with [alloy forgery](https://modrinth.com/mod/alloy-forgery) in isolation.

**Comment by gliscowo** [comment]
What versions of the game, which loader, which version of owo... Ideally a log please

**Comment by sleepingdragoninn** [comment]
0.11.1 with qfapi - issue doesn't occur with fapi. https://mclo.gs/AABAP8v

**Comment by Noaaan** [comment]
Can confirm this happening in Minecraft 1.20 with QFAPI 7.0.4, owo-lib 0.11.0, and Quilt Loader 0.19.1. The issue does not manifest unless an owo-item-group is registered, as including any arbritrary mod I.E. Ecotones, then everything works like normal. If I add Alloy Forgery or Mythic Metals the scroll bars disappear. 

Its worth noting that the "Search Items" tab keeps its scroll bar if an owo-item-group is present, although from what I have seen it cases with more mods it can be somewhat inconsistent on what groups get a scroll bar or not.

![image](https://github.com/wisp-forest/owo-lib/assets/4163353/f56b22e8-d490-489a-9541-716877e60150)


![image](https://github.com/wisp-forest/owo-lib/assets/4163353/3fbe1a83-70f6-4f30-8d25-d89119f7dd49)

**Comment by gliscowo** [comment]
Fixed in 5317684, scheduled for timely release in 0.11.2
