### ISSUE TITLE
Handshake Failure

### ISSUE THREAD

**Issue by RotokEralil** [wisp-forest/owo-lib#15]
How do you configure handshake support?
I currently run a velocity proxy with fabricproxy, and owo prevents anyone from joining due to the error below. 
I remove owo and the mod that requires it and have no problems.
![image](https://user-images.githubusercontent.com/96855797/150894393-f5502b84-27fa-4104-8bbb-37e534714dd9.png)

**Comment by BasiqueEvangelist** [comment]
oωo handshakes aren't currently supported with Velocity, as it drops custom payload login packets.
Velocity support is planned for the next minor release.

**Comment by BasiqueEvangelist** [comment]
We ended up fixing this with a Velocity plugin. The plugin is at https://github.com/BasiqueEvangelist/OwoVelocityPlugin/releases/tag/0.1.0 - you should install it on the proxy and report back whether it worked or not.

**Comment by RotokEralil** [comment]
I will have our server owner update.
To confirm; just add this to our proxy server (velocity) and the latest version of owo to our backend (the fabric) server?
Are there any configs that need to be set?

**Comment by BasiqueEvangelist** [comment]
> I will have our server owner update. To confirm; just add this to our proxy server (velocity) and the latest version of owo to our backend (the fabric) server? Are there any configs that need to be set?

You can just add the plugin to the proxy server, no configs

**Comment by RotokEralil** [comment]
Add the fabric version to the backend server and the plugin version to the proxy, or just install the proxy (no backend requried)?

**Comment by BasiqueEvangelist** [comment]
> Add the fabric version to the backend server and the plugin version to the proxy, or just install the proxy (no backend requried)?

Just add the plugin to the proxy, it should work with the old owo version
