### ISSUE TITLE
Forge port?

### ISSUE THREAD

**Issue by FlorentTomi** [wisp-forest/owo-lib#151]
Hey guys!
I've been really enjoying this library. It is, in my opinion, one of the most well done utility library out there.
I think it deserve to be more used and one of the limitation is the lack of Forge compatibility. 
Is that a deliberate choice?
Can we expect a Forge port in the future?

**Comment by gliscowo** [comment]
Yes, that is indeed a deliberate choice. Everyone on the team here primarily develops for Fabric and is plenty busy with other projects (and, you know, life). We do not have the capacity or any interest to maintain a version of this library for a separate loader with fundamentally different architecture and release cycle
Cheers
