### ISSUE TITLE
[owo-config] Is it possible to add a config badge?

### ISSUE THREAD

**Issue by c0nstexpr** [wisp-forest/owo-lib#160]
Adding badge config like
```
  "custom": {
    "modmenu": {
      "badges": [
        "library"
      ]
    }
  }
```
in fabric.mod.json causing the mod disappear in modmenu

**Comment by Noaaan** [comment]
Why would this be needed? owo-lib *is* a library, which by standard is filtered out by Mod Menu

**Comment by c0nstexpr** [comment]
> Why would this be needed? owo-lib _is_ a library, which by standard is filtered out by Mod Menu

 I noticed that Mod Menu by default filtered out all library mod and mod settings was actually initialized.
Close the issue.
