### ISSUE TITLE
Cursor doesn't return to default settings after closing screen with ESC key

### ISSUE THREAD

**Issue by xMelonekMaX** [wisp-forest/owo-lib#167]
I noticed it on my mod and on Isometric Renders
![cursor bug](https://github.com/wisp-forest/owo-lib/assets/96833801/50e8a7d2-98e1-43cc-b4ff-a10b22788ad8)

**Comment by gliscowo** [comment]
We haven't been able to reproduce this issue on either Linux or Windows, using a variety of different screens from different mods. What is the exact setup you used to trigger the bug? To this end, please provide your `latest.log` file from a time the issue happened

Cheers

**Comment by xMelonekMaX** [comment]
[latest.log](https://github.com/wisp-forest/owo-lib/files/12437633/latest.log)

I also noticed that the cursor resets when I open creative inventory (not survival)
![creative](https://github.com/wisp-forest/owo-lib/assets/96833801/f7dda2bd-7b92-4f37-95bc-763ca91fa059)
