### ISSUE TITLE
Add a Color Picker to OWO Lib Library

### ISSUE THREAD

**Issue by copyandexecute** [wisp-forest/owo-lib#168]
I'm a devoted user of owo-lib and truly appreciate its functionality. Could we consider adding a Color Picker to the library? This feature would be a fantastic enhancement, allowing us to fine-tune visual elements seamlessly. Your expertise would undoubtedly make it an invaluable addition.

Looking forward to your thoughts on this.

**Comment by BasiqueEvangelist** [comment]
There already is one, though.
If you make a field in your config that has the type [`io.wispforest.owo.ui.core.Color`](https://github.com/wisp-forest/owo-lib/blob/1.20/src/main/java/io/wispforest/owo/ui/core/Color.java), you can then customize that config option via a color picker modal
Alternatively, if you want a widget, [`io.wispforest.owo.ui.component.ColorPickerComponent`](https://github.com/wisp-forest/owo-lib/blob/1.20/src/main/java/io/wispforest/owo/ui/component/ColorPickerComponent.java) should be what you need.

**Comment by copyandexecute** [comment]
You're welcome! I couldn't find it either because there was no static builder in Components, but now I'll proceed to work directly on my UI.
