### ISSUE TITLE
Incompatibility with Untranslated Items

### ISSUE THREAD

**Issue by ghost** [wisp-forest/owo-lib#172]
owo-lib - 0.11.1 is conflicting with [Untranslated items](https://www.curseforge.com/minecraft/mc-mods/untranslated-items) v1.7 for fabric.
[crash-2023-08-28_15.54.14-client.txt](https://github.com/wisp-forest/owo-lib/files/12451267/crash-2023-08-28_15.54.14-client.txt)

**Comment by gliscowo** [comment]
Given that Untranslated Items is both closed source *and* presumably doing some quite invasive modifications to make this problem occur, we cannot do anything further to resolve it. If you need it fixed, contact the mod's author (which, as far as I can tell, you've already done) and hope that they can engineer a fix with insight into their mod's code

Cheers
