### ISSUE TITLE
Advertisements In Logs

### ISSUE THREAD

**Issue by sylv256** [wisp-forest/owo-lib#174]
Are you kidding me?
![image](https://github.com/wisp-forest/owo-lib/assets/18603248/21811420-5a73-4508-bf77-3a2b64776d8a)

**Comment by Noaaan** [comment]
This was never intended as an advertisement, but we definitely understand why it may come off as such. We will change/remove this line from Wisdom. Thanks for letting us know.

**Comment by BasiqueEvangelist** [comment]
> Are you kidding me? ![image](https://user-images.githubusercontent.com/18603248/264225668-21811420-5a73-4508-bf77-3a2b64776d8a.png)

https://github.com/wisp-forest/owo-lib/blob/1.20/src/main/java/io/wispforest/owo/util/Wisdom.java#L48

**Comment by sylv256** [comment]
> > Are you kidding me? ![image](https://user-images.githubusercontent.com/18603248/264225668-21811420-5a73-4508-bf77-3a2b64776d8a.png)
> 
> https://github.com/wisp-forest/owo-lib/blob/1.20/src/main/java/io/wispforest/owo/util/Wisdom.java#L48

I thoroughly dislike the attitude of this team and how you all have treated the BC23 organizers.

**Comment by chyzman** [comment]
[i gochu](https://github.com/wisp-forest/owo-lib/pull/175)

**Comment by gliscowo** [comment]
In light of #195 being merged, this issue shall now be closed
