### ISSUE TITLE
Protocol version for channel ... does not match. Expected: 0, received: ?0?0MissingVersion

### ISSUE THREAD

**Issue by femboyfin** [wisp-forest/owo-lib#176]
I'm running a Fabric (1.20.1) modpack behind Velocity (3.2.0-SNAPSHOT-265) and running into the same issue with multiple mods. I'm using owo-velocity (0.1.2) on the Velocity instance (to avoid [the handshake failure problem](https://docs.wispforest.io/faq/#i-get-disconnected-due-to-an-oo-handshake-failure-when-trying-to-join-a-server)) and owo-lib (0.11.1+1.20) on both the Fabric server and client which are all latest at the moment.

First got kicked on join with the following message mentioning Useful Backpacks;

```
[Netty Epoll Server IO #3/INFO]: Disconnecting com.mojang.authlib.GameProfile@ccd593c[id=<null>,name=blowhole,properties={},legacy=false] (/127.0.0.1:35328): Protocol version for channel usefulbackpacks:slot_mod does not match. Expected: 0, received: ?0?0MissingVersion
```

and then after disabling that mod I get a similar message with U Team Core;

```
[Netty Epoll Server IO #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@6a9b4df6[id=<null>,name=blowhole,properties={},legacy=false] (/127.0.0.1:33664): Protocol version for channel uteamcore:network does not match. Expected: 1.20.1-1, received: ?0?0MissingVersion
```

which made me suspect owo-lib was the issue.

**Comment by BasiqueEvangelist** [comment]
I'm a bit confused. Are you sure this isn't just U Team Core being incompatible with proxies? It also has a login handshake that's separate from owo-lib's.

**Comment by femboyfin** [comment]
You're right- that does seem to be the case, there's actually already an issue open about it as well (https://github.com/MC-U-Team/U-Team-Core/issues/330). I saw the OwOMissingVersion bit and assumed it was owo-lib, sorry about that!

**Comment by Neubulae** [comment]
It wasn't OwOMissingVersion, it was badly converted unicode, it should be 😿😿MissingVersion instead...
