### ISSUE TITLE
Game crashes when trying to join world with mods that have owo listed as a requirement

### ISSUE THREAD

**Issue by miaumattimc** [wisp-forest/owo-lib#185]
My installation crashes when trying to join a world or server. With owo-lib itself installed, everything works fine but as soon as I add mods that have it as a dependency (I tried DeathLog and Isometric Renders) the game crashes instantly with the following crash report (including System information like fabric/mc version and mods):

[crash-2023-10-15_16.19.21-client.txt](https://github.com/wisp-forest/owo-lib/files/12909792/crash-2023-10-15_16.19.21-client.txt)

EDIT: I could fix the issue by moving everything to a brand new installation. I don't know why that worked. Would appreciate a human-readable version of the crash report tho :')

**Comment by Noaaan** [comment]
I believe this is a confirmed issue that happens with FancyMenu. It should be fixed with the upcoming release of it (version 3+)

**Comment by miaumattimc** [comment]
I found the problem, the servers.dat_old is causing the crashes. If it is deleted, everything works fine.
