### ISSUE TITLE
[Suggestion] Features port to older versions

### ISSUE THREAD

**Issue by zeresss** [wisp-forest/owo-lib#189]
I am working on a mod and used owo lib to add config to my mod. When I started porting my mod to older versions of minecraft I realised that owo lib does not have a config package for 1.18 and 1.17 versions. Are there any plans to port owo lib features to 1.18 and 1.17? If so, can I receive more information when it can be released?

**Comment by gliscowo** [comment]
We generally do not do backports on any of our mods or libraries - especially not to versions which are this out-of-date. If you find somebody else (or potentially yourself) who is willing to do it, you're free to go ahead (and potentially PR the result for us to publish)

Cheers
