### ISSUE TITLE
Handshake failure with v0.5.2 connecting to a modded server

### ISSUE THREAD

**Issue by mbrozzo** [wisp-forest/owo-lib#19]
I am openin this issue, but I am not sure if this problem is on your part, but I have seen another closed issue similar to this one, so even if this is not your problem, you may have some helpful insight even if it is not your problem.

Me and my friends are currently playing in a modded Minecraft server created by me on Aternos. It was working fine for everybody but one of us, who was getting an "[owo] handshake failure" error when trying to connect. He was using a modem with a SIM card to connect to the internet, then he switched to ADSL (which he would not use as it is worse than the SIM card) and he could connect normally.

The server uses Minecraft 1.18.1, Fabric 0.13.3, Java 17, owo v0.5.2.

Do you know if it is possible to make the server work with that other connection? Or do you at least know where is the problem?

Thank you in advance!

**Comment by BasiqueEvangelist** [comment]
Could you send the entire handshake failure message?

**Comment by mbrozzo** [comment]
![image](https://user-images.githubusercontent.com/22538059/159185286-23fed5f6-b3e0-41dc-8b2d-0a88142560bd.png)

I am sorry but I am not finding the error in the log, should it be there?

**Comment by Alex-gnzl** [comment]
Experiencing this as well. MC 1.18.1, Fabric 0.13.3, owo 0.5.2. Only relevant logs:
```
[20:36:32] [Netty Epoll Server IO #2/INFO]: [Handshake] Handshake failed, client did not respond to channel query
[20:36:32] [Server thread/INFO]: (*user info redacted*) lost connection: [oωo] §chandshake failure
```
EDIT: I can connect fine with the same mods, only one user can't.

**Comment by BasiqueEvangelist** [comment]
> Experiencing this as well. MC 1.18.1, Fabric 0.13.3, owo 0.5.2. Only relevant logs:
> 
> ```
> [20:36:32] [Netty Epoll Server IO #2/INFO]: [Handshake] Handshake failed, client did not respond to channel query
> [20:36:32] [Server thread/INFO]: (*user info redacted*) lost connection: [oωo] §chandshake failure
> ```
> 
> EDIT: I can connect fine with the same mods, only one user can't.

Does that user have a different set of mods? Is the server behind a proxy?

**Comment by Alex-gnzl** [comment]
Allegedly the same, I'm going to make them use my polymc instance to see if it's user error. No proxy. Will edit this comment ASAP.

Edit: It was user error likely, even though they claimed to not have messed with mods. Sorry for bothering you!

**Comment by mbrozzo** [comment]
> Does that user have a different set of mods? Is the server behind a proxy?

I know you weren't asking me, but I can confirm that in my case the user who experiences the problem was using a Minecraft instance identical to mine (and I can connect without issues), as I even ended up giving him a copy of my .minecraft folder and the same Java 17 runtime. Besides, since he could connect when switching from the SIM card to the ADSL, I think the set of mods is not the problem.

Regarding the proxy, I don't know if Aternos servers are behind proxies, but maybe his modem with the SIM card manages the IP connection in some unusual way?

Btw, I was searching for the handshake error in the client logs. Now that I know that they are in the server logs I'll ask him to try and connect to the server using the SIM card and look in the server logs to see the error is the same as @Alex-gnzl's.

**Comment by mbrozzo** [comment]
Important update: it was my fault as I had them use the server address without the port (*.aternos.me instead of *.aternos.me:[port]). I found it out when a similar problem happened to another friend, but it was not your mod to cause it.

Sorry for the false alarm,

Not sure if it is the same problem that @Alex-gnzl is having.

**Comment by gliscowo** [comment]
Given that in both of these cases the problem seems to have originated from user error, I will go ahead and close this. Thank you for thoroughly testing this and finding the problem
Cheers
