### ISSUE TITLE
"oωo > handshake failure", incompatible client (minecraft craked version)

### ISSUE THREAD

**Issue by FrAleex** [wisp-forest/owo-lib#196]
Hello,

I'm here to search for a solution, I'm curently playing with a friend with minecraft craked edition,
And he can't connect on the server because of that, how can I turn OwO on offline mode ?

Here the part of the log :
[19:55:08] [Netty Epoll Server IO #15/INFO]: [Handshake] Handshake failed, client did not respond to channel query
[19:55:08] [Server thread/INFO]: com.mojang.authlib.GameProfile@5abca917[id=<null>,name=labiscote,properties={},legacy=false] (/xx.xxxx.xxxx.xxxx:xxx) lost connection: oωo > §chandshake failure
incompatible client

Thanks for your time to read.

**Comment by FrAleex** [comment]
Hello,

If you want to know what modpack I use,
It is DarkRPG V7.5.3

Have a good day.

**Comment by FrAleex** [comment]
I don't know if I fixed it now but I try the -Dowo.handshake.disable <true|false>

**Comment by gliscowo** [comment]
Unfortunately, we cannot provide you with support when playing the game without a proper license - this would violate GitHub's acceptable use policy (and our own moral values, but that's beside the point)

As such, I'll have to close this issue
