### ISSUE TITLE
[Issue] Colour Picker doesn't prevent interacting

### ISSUE THREAD

**Issue by A5ho9999** [wisp-forest/owo-lib#199]
Version: 0.12.0-pre.1+1.20.3

The Colour picker doesn't prevent you from interacting with what is behind it.

- Config Tooltips/Descriptions are still displayed
- Buttons can still be highlighted (Clicking closes colour picker)
- Scroll wheel on a slider still changes slider while colour picker is visible

![tooltips](https://i.imgur.com/IIcjdQl.png)

**Comment by gliscowo** [comment]
Hey, thanks for reporting this! It's now been fixed as part of owo's [0.12.1 release](https://modrinth.com/mod/owo-lib/version/0.12.1+1.20.3)

Cheers
