### ISSUE TITLE
ClickEvent that opens a url on LabelCompenent went wrong

### ISSUE THREAD

**Issue by zly2006** [wisp-forest/owo-lib#214]
If you add a label component with a open url click event, the game will ask if you are sure to open that url, after you click yes or no, the screen should be the original screen.

however, it is a UtilityScreen, I tried to investigate it and found `io.wispforest.owo.ui.component.LabelComponent#textClickHandler`, I think this is possible why it becomes UtilityScreen -- it created a LinkConfirmScreen as the parent is itself.

**Comment by gliscowo** [comment]
Thanks for your report! This has now been fixed in [0.12.5](https://modrinth.com/mod/owo-lib/version/0.12.5+1.20.3)

Cheers
