### ISSUE TITLE
Errors with Iris v1.6.11-v1.6.17

### ISSUE THREAD

**Issue by GJdude** [wisp-forest/owo-lib#226]
Version 0.11.2+1.20 of this mod in 1.20.1 is causing this rather infamous error when paired with newer version of Iris Shaders, including v1.6.17 which I'm currently using. Version v1.6.10 works fine. Slows down pretty much every loading screen and causes any loaded resource packs to unload. Maybe it also has something to do with updating Sodium from 0.5.3 to 0.5.8 as well? At best I'm hoping this just needs a little version bump or compatibility tweak. (First error shows up in Mod Menu, second on main menu)
![Untitled](https://github.com/wisp-forest/owo-lib/assets/83022658/b5cba97d-7d49-4317-b361-20d7ada66259)
![Untitled2](https://github.com/wisp-forest/owo-lib/assets/83022658/c982b9a1-96e8-4005-8684-0233e927abbf)
I'm also using a fair few other mods, but even stripping things down, it still happens.
Here's the log: (some other mods seem to be acting up, but don't worry about that)
[latest.log](https://github.com/wisp-forest/owo-lib/files/14968127/latest.log)

**Comment by Noaaan** [comment]
This log is reporting that you are using `owo 0.11.1+1.20`. Could you try reproducing this issue/providing a log with the intended version?

**Comment by GJdude** [comment]
I'm playing on MC 1.20.1, are there newer versions that support it? The latest doesn't seem to.

**Comment by Noaaan** [comment]
As you mentioned, `0.11.2+1.20` is the latest version

**Comment by GJdude** [comment]
Oh, I see! Strange, I thought I had that one in the folder. I'll give it another try.

**Comment by GJdude** [comment]
Error is still happening with 0.11.2+1.20. Here's the log.
[latest.log](https://github.com/wisp-forest/owo-lib/files/14968161/latest.log)

**Comment by GJdude** [comment]
Got a little more info with further testing. Everything seems to work fine when _only_ Iris is present. Bug may be connected to the compatiblity mod iris-flywheel-compat-1.20.1-0.2.1. Compat issues from one mod after another are layering on top of each other, so I'll just play without Iris for now and see if future updates smooth things out.

**Comment by GJdude** [comment]
Iris Flywheel Compat has a newer version on curseforge (1.20.1-0.2.4) that appears to solve this issue.
