### ISSUE TITLE
aternos handshake crash

### ISSUE THREAD

**Issue by memphismc** [wisp-forest/owo-lib#227]
cant join the server due to this mod

[latest.log](https://github.com/wisp-forest/owo-lib/files/15045582/latest.log)

**Comment by Dragon-Seeker** [comment]
Without more information about the given modpack/modlist combined with version info about Minecraft or owolib we can not assist with the issue.

**Comment by memphismc** [comment]
the log file is literally right there in my message

also i gave up on aternos

**Comment by Noaaan** [comment]
A regular log contains more info than this. If you are able to reproduce this issue, please provide a full log. Fabric always logs what mods you are using first thing in the file, which usually helps pointing to the issue.
As Blodgharm mentioned, a handshake error usually occurs whenever you have mismatching mods between your client and your server. Make sure that you are using the same on both ends.

**Comment by Definitelyblank** [comment]
Handshake crash because of this mod which is involved in the Prominence 2 modpack;
owo version is 1.20.1 /0.11.2.jar
![image](https://github.com/wisp-forest/owo-lib/assets/170118296/eae8fd6f-f0f9-4867-88fc-121cc055953c)

**Comment by Noaaan** [comment]
This is not a crash, it is an error. You are missing Mythic Metals on your client

**Comment by Definitelyblank** [comment]
I reinstalled the mod specifically and the whole modpack and client again. So there wont be anything wrong with the client.
but i found the problem, the server was configured some mods to match their server hardware. Since i could join other servers/official prom2 server but not theirs. Still thank you for the time to respond!
