### ISSUE TITLE
Crashes minecraft 1.20.5

### ISSUE THREAD

**Issue by Bumer-32** [wisp-forest/owo-lib#228]
Owo lib doesn`t support mc 1.20.5

Owo lib: 0.12.6+1.20.3
Fabric ver: latest
Other mods: fabric api latest

nothing more sorry

crash:
[crash-2024-04-27_12.54.46-client.txt](https://github.com/wisp-forest/owo-lib/files/15137790/crash-2024-04-27_12.54.46-client.txt)

**Comment by Noaaan** [comment]
Will most likely be solved by #217

**Comment by Bumer-32** [comment]
nah, waiting...

**Comment by gliscowo** [comment]
🤨

**Comment by gliscowo** [comment]
https://modrinth.com/mod/owo-lib/version/cFeG2MJS

**Comment by Bumer-32** [comment]
is new version on maven? https://maven.wispforest.io/#/releases/io/wispforest/owo-lib theres only 0.12.3-pre.3+1.20.3

**Comment by Noaaan** [comment]
0.12.7+1.20.5 was pushed very recently to the Maven
