### ISSUE TITLE
Crash when joining the server (1.20.5)

### ISSUE THREAD

**Issue by xMelonekMaX** [wisp-forest/owo-lib#229]
For example hypixel.net
[crash-2024-04-29_15.21.17-client.txt](https://github.com/wisp-forest/owo-lib/files/15149740/crash-2024-04-29_15.21.17-client.txt)

**Comment by gliscowo** [comment]
Fixed in [0.12.7](https://modrinth.com/mod/owo-lib/version/cFeG2MJS), thanks for reporting
Cheers
