### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by molotov11235813** [wisp-forest/owo-lib#23]
java.lang.NoClassDefFoundError: Could not initialize class io.wispforest.owo.network.OwoHandshake
[crash-2022-04-05_19.29.24-client.txt](https://github.com/gliscowo/owo-lib/files/8422472/crash-2022-04-05_19.29.24-client.txt)

**Comment by gliscowo** [comment]
We need more information to figure out what's going on here, namely: What modpack are you running? Does this always happen? Have you fixed it by now?

**Comment by gliscowo** [comment]
As this issue has now been stale for almost two months, I'll go ahead and close it for the time being. Feel free to reopen it if the problem persists
Cheers
