### ISSUE TITLE
Joining the world the first time after starting the game fails

### ISSUE THREAD

**Issue by xMelonekMaX** [wisp-forest/owo-lib#230]
Quilt 1.20.5
https://github.com/wisp-forest/owo-lib/assets/96833801/79d9225e-e6c1-407f-8c7a-748b5e969421

[latest.log](https://github.com/wisp-forest/owo-lib/files/15176345/latest.log)

**Comment by xMelonekMaX** [comment]
Same situation on Fabric 1.20.5

**Comment by gliscowo** [comment]
Fixed in [0.12.8](https://modrinth.com/mod/owo-lib/version/0.12.8+1.20.5), thanks for reporting!
