### ISSUE TITLE
Error loading class: net/minecraft/class_8673

### ISSUE THREAD

**Issue by Chazzwazzler** [wisp-forest/owo-lib#241]
On 1.20.6, I get the following errors from owo lib 0.12.8 on my server. I tried removing all of my other mods and leaving only fabric api and owo lib, and I still get the same errors. I also tried various versions of fabric api and owo lib as well as resetting my server and I still get the errors.
` Error loading class: net/minecraft/class_8673 (java.lang.ClassNotFoundException: net/minecraft/class_8673)`
` @Mixin target net.minecraft.class_8673 was not found owo.mixins.json:ClientCommonNetworkHandlerAccessor from mod owo`
` Error loading class: xyz/nucleoid/server/translations/impl/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: xyz/nucleoid/server/translations/impl/language/SystemDelegatedLanguage)`

The server still launches after this, but any mod using owo lib doesn't work. Modrinth said that owo lib supports 1.20.6. Does it not?

**Comment by gliscowo** [comment]
owo should most definitely work on 1.20.5/6. The errors you sent are not actually errors, merely warnings and they do not have any further significance. If you're still experiencing this problem, please send us your entire log as per our [contributing guidelines](https://github.com/wisp-forest/.github/blob/5dff6a3cc8567a95f8d72e3d0cc852a7f2db7364/CONTRIBUTING.md)

Cheers
