### ISSUE TITLE
Crash when opening Shop (Numismatic Overhaul)

### ISSUE THREAD

**Issue by Skullians** [wisp-forest/owo-lib#243]
Heya.

This is an odd crash.
I'm in the process of creating a custom modpack. It includes latest owolib and latest numismatic overhaul.

One of us (without ANY additional mods), is crashing when opening a Numismatic Overhaul.
I myself and some others have tried and do not crash.

I'm lost here.
They've tried reinstalling the modpack, etc.
Here's the crash log:

https://mclo.gs/nIpvLZD

**Comment by Dragon-Seeker** [comment]
Conflict with Charm, install this to fix the issue: https://legacy.curseforge.com/minecraft/mc-mods/charm-fixer/files/4081618
