### ISSUE TITLE
Crash with Fabric API 0.100.0+1.20.6

### ISSUE THREAD

**Issue by srnyx** [wisp-forest/owo-lib#245]
Doesn't occur with Fabric API 0.99.4+1.20.6 (prior release)

https://mclo.gs/ec5OPvs

**Comment by rotgruengelb** [comment]
Can confirm!

**Comment by Koxae** [comment]
Same for me

**Comment by Dragon-Seeker** [comment]
Know issue, for now please use previous version of FAPI as a work around

**Comment by gliscowo** [comment]
This has now been fixed in [0.12.9](https://modrinth.com/mod/ccKDOlHs/version/gizS7nlP)
Cheeres
