### ISSUE TITLE
[incompatibility report] Update for 1.21

### ISSUE THREAD

**Issue by c0nstexpr** [wisp-forest/owo-lib#246]
As title suggested. Currently the mod is broken

> [14:14:36] [main/ERROR]: Mixin apply for mod owo failed owo.mixins.json:ui.ScreenMixin from mod owo -> net.minecraft.class_437: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyArg annotation on injectProperLinkSource could not find any targets matching 'Lnet/minecraft/class_437;method_25428(Z)V' in net.minecraft.class_437. Using refmap owo-lib-refmap.json [PREINJECT Applicator Phase -> owo.mixins.json:ui.ScreenMixin from mod owo -> Prepare Injections ->  -> modify$bob000$owo$injectProperLinkSource(Lnet/minecraft/class_437;)Lnet/minecraft/class_437; -> Parse]

**Comment by Noaaan** [comment]
Will be fixed by https://github.com/wisp-forest/owo-lib/pull/242
After all, 1.21 unsurprisingly broke a ton of mods with very extensive changes

**Comment by c0nstexpr** [comment]
New version was tested in my mod project
