### ISSUE TITLE
NeoForge?

### ISSUE THREAD

**Issue by dima-dencep** [wisp-forest/owo-lib#253]
Some features in this library are really useful, I'd like to use them on neoforge, like ui for example.

NeoForge is more responsive, for example it has an equivalent to your Rich Translations

**Comment by BasiqueEvangelist** [comment]
> for example it has an equivalent to your Rich Translations

Guess who contributed that to Neo? :wink: 

We're currently working on a NeoForge version of owo-lib, though it's not really production ready at the moment. [Here's the branch if you're interested.](https://github.com/Dragon-Seeker/owo-lib/tree/1.21-Neo)

**Comment by dima-dencep** [comment]
Yeah, I know, thank you ❤️🦊

**Comment by gliscowo** [comment]
Closing as completed, for apparent reasons
