### ISSUE TITLE
owo Handshake failure

### ISSUE THREAD

**Issue by WalEl6512** [wisp-forest/owo-lib#26]
EThe version on server and Client are the same, all my friends can join wiht it exept me. Why is this so?

**Comment by gliscowo** [comment]
What specific error are you getting? It would also be good if you can include the full log from both the server and your client

**Comment by WalEl6512** [comment]
I can close the issue now. I found the problem, it was a incompatibly with the server and client caused by wraith-alloy-forgery and Dimensional Doors. The server was missing a mod, not the client and owo for some strange reason had a problem with that

**Comment by BasiqueEvangelist** [comment]
> and owo for some strange reason had a problem with that

The entire point of the OwO handshake is to break when network packet channels don't match :stuck_out_tongue:
