### ISSUE TITLE
cant hover over enchantented book in villager trade

### ISSUE THREAD

**Issue by Flintley** [wisp-forest/owo-lib#269]
![image](https://github.com/user-attachments/assets/a721892c-24a8-4989-ab4f-604e9534b610)

client version:
Minecraft 1.20.4 - Fabric Loader 0.15.11

mod list:
- fabric-api 0.97.1+1.20.4
- owo 0.12.6+1.20.3

**Comment by gliscowo** [comment]
I cannot reproduce this problem with just the mods your described, as such we'll need your `latest.log` file from a run of the game where this problem occurred - as we mention in our [contributing guidelines](https://github.com/wisp-forest/.github/blob/5dff6a3cc8567a95f8d72e3d0cc852a7f2db7364/CONTRIBUTING.md). I believe it is also apparent from the screenshot you attached that you had significantly more mods installed than just owo and Fabric API - this is important context

**Comment by gliscowo** [comment]
If this problem is still relevant and you can supply us with the required log, please send it here and reopen the issue - I'll close it for now

Cheers
