### ISSUE TITLE
Multiple mods crash with owo-lib

### ISSUE THREAD

**Issue by HacoKavanah** [wisp-forest/owo-lib#272]
[crash-2024-07-19_12.20.11-server.txt](https://github.com/user-attachments/files/16310476/crash-2024-07-19_12.20.11-server.txt)
[crash-2024-06-26_19.41.41-server.txt](https://github.com/user-attachments/files/16310478/crash-2024-06-26_19.41.41-server.txt)
[crash-2024-07-19_12.33.28-server.txt](https://github.com/user-attachments/files/16310479/crash-2024-07-19_12.33.28-server.txt)
It appears the mods Oritech, Mythic Metals and Trickster all crash with owo-lib. Turning these mods off fixes the issue but its clear owo-lib is causing it.

**Comment by Dragon-Seeker** [comment]
Honestly confused how such is even occurring with the method being called injected within a mixin so something is going wrong with applying such or something. A full log of the game run would help to better pinpoint if such is mixin related issues.

**Comment by gliscowo** [comment]
If this problem is still relevant and you can supply us with proper logs, please send them and reopen the issue - I'll be closing it for now

Cheers
