### ISSUE TITLE
Forced installation?

### ISSUE THREAD

**Issue by pil0lo** [wisp-forest/owo-lib#275]
It keeps telling me to install this mod if I don't have it?
Can't I turn this off?

**Comment by gliscowo** [comment]
If this happens then that means some other mod needs owo and is using owo-sentinel to ease the installation for you. So no, besides removing that other mod you can't turn it off because you won't be able to launch your game without owo

Cheers

**Comment by pil0lo** [comment]
문제의 모드"disenchanter-0.1.9+1.21" 작동도 안되면서 "owo-lib"모드를 강제적으로 설치하게 만드는 모드.
