### ISSUE TITLE
`ConfigWrapper` shouldn't clinit `Screen`

### ISSUE THREAD

**Issue by BasiqueEvangelist** [wisp-forest/owo-lib#285]
Currently, `ConfigWrapper` [clinits `ConfigScreen`](https://github.com/wisp-forest/owo-lib/blob/1.21/src/main/java/io/wispforest/owo/config/ConfigWrapper.java#L91-L94), which clinits Screen because it's its superclass.
`Screen` has a static `RotatingCubeMapRenderer ROTATING_PANORAMA_RENDERER` field which is initted in `<clinit>` and which captures the current `MinecraftClient`, which if it's early enough in the game will be null. This will cause a NPE later in the runtime.

**Comment by gliscowo** [comment]
Fixed as of [0.12.12](https://modrinth.com/mod/owo-lib/version/0.12.12+1.21)
