### ISSUE TITLE
Dealing with Immediately Fast crash that isn't easily replicable in small modpacks

### ISSUE THREAD

**Issue by Barerock** [wisp-forest/owo-lib#294]
It's replicable with one or the other mod disabled, and I know owo has issues with IF and I've seen it have issues in much smaller modpacks in the past, something like 100 mods vs 300 now. owo and IF consistently have issues but the dev of IF is unwilling to entertain the possibility.

There's some kind of critical mass to this issue and I can't find what's causing it. I know for a fact that IF is interacting with owo in a way that causes this, but there's a middleman instigating startup crashes to happen _way_ more often than I've seen before, something like 60% of startups fail right now whereas with just the two and things that use oWo, this crash occurs very rarely.

[latest.log](https://github.com/user-attachments/files/16826028/latest.log)
[crash-2024-08-31_16.34.13-client.txt](https://github.com/user-attachments/files/16826029/crash-2024-08-31_16.34.13-client.txt)

**Comment by gliscowo** [comment]
Seeing as this is a Connector problem, please report it to the Connector developers first - as the large disclaimer at the top of your crash log clearly tells you to do. If they determine that this is in fact an owo problem (which I highly doubt, nobody's experiencing this on Fabric), please come back to us

Cheers
