### ISSUE TITLE
Ideas for improvements (will add to this when I find out more that can be done)

### ISSUE THREAD

**Issue by oliviathevampire** [wisp-forest/owo-lib#3]
Here are my ideas:
- Option to choose how many tabs can be stacked other than the default 4, you could for example choose 6 and it would add on top and bottom.
- Option for compact tabs (see texture idea I sent you)
- Option to change the name of of the item group based off the tab you're in
- Option to select multiple tabs at the same time or none.
- Option to have sub-tabs (unsure about this)
- Force the tabs to only add items which is in their original tab

**Comment by gliscowo** [comment]
Progress Report: 
- ~~Option to choose how many tabs can be stacked other than the default 4, you could for example choose 6 and it would add on top and bottom.~~ ✅
- Option for compact tabs (see texture idea I sent you)
- ~~Option to change the name of of the item group based off the tab you're in~~ ✅
- Option to select multiple tabs at the same time or none.
- Option to have sub-tabs (unsure about this)
- Force the tabs to only add items which is in their original tab
