### ISSUE TITLE
handshake error, my game aint starting

### ISSUE THREAD

**Issue by DuskO7** [wisp-forest/owo-lib#31]
it says incompatible server, when they have the exact same mods

**Comment by DuskO7** [comment]
it says [owo] handshake failure
incompatible server

**Comment by Noaaan** [comment]
There are more reasons for this error to occur, see the FAQ: https://docs.wispforest.io/faq/#i-get-disconnected-due-to-a-oo-handshake-failure-incompatible-server-when-trying-to-join-a-server
If you are fully certain that your server is not behind a proxy, please provide us with logs from the client/server in regards to why they are incompatible.

**Comment by DuskO7** [comment]
[latest.log](https://github.com/wisp-forest/owo-lib/files/8882695/latest.log)
^^^
here it is, thats my client, and below is my server, all the versions match up. 
[latest (4).log](https://github.com/wisp-forest/owo-lib/files/8882696/latest.4.log)

**Comment by Noaaan** [comment]
It seems that you forgot to install the [Fabric Loader](https://fabricmc.net/) on the server. Please install it and try to load your mods again.

**Comment by DuskO7** [comment]
fabric loader is on, with the server launch, the server launch properties, and server.jar, and vanilla.jar

**Comment by DuskO7** [comment]
its all there

**Comment by Noaaan** [comment]
Make sure you are launching with the correct jar, as the log you sent us literally comes from a vanilla server

**Comment by gliscowo** [comment]
As this issue almost certainly does not stem from a bug in owo, but instead user error, I will go ahead and close this
Cheers
