### ISSUE TITLE
Document the owo.handshake.disable system variable

### ISSUE THREAD

**Issue by CamperSamu** [wisp-forest/owo-lib#32]
This system variable can be useful when trying to make mods using owo-lib working with mods like [PolyMC](https://github.com/TheEpicBlock/PolyMc).
I get that it's not an intended use of the lib or in the library's focus at all but to someone this can be helpful.
Maybe it can be listed as a unsupported use of the library, the mods using this library and it should be used at your own risk?

**Comment by CamperSamu** [comment]
Also I haven't looked at the code enough, but I think that any system variable should be at least mentioned on the docs.

**Comment by gliscowo** [comment]
Thanks for giving us a heads up about this, there is a now [a page in the docs](https://docs.wispforest.io/owo/system-properties/) which explains all system properties oωo provides
Cheers
