### ISSUE TITLE
Most Recent Update Crashes with Tech Reborn Installed

### ISSUE THREAD

**Issue by rrwatson** [wisp-forest/owo-lib#322]
Hey there,
Pretty straightforward. Looks like the newest version crashes when Tech Reborn is installed. 0.12.10 is functional however!

**Comment by Dragon-Seeker** [comment]
Any crash log or log as without it its hard to know whats going wrong

**Comment by rrwatson** [comment]
Hey there,
Looks like it's not exclusive to Tech Reborn. I tried running this mod and Tech Reborn by itself and it didn't crash. The exit code directly specifies Tech Reborn however. Trying to find the minimum number of mods that cause this crash right now.

**Comment by rrwatson** [comment]
Closing this. I narrowed it down to Tech Reborn, owo-lib, and simplecopperpipes. Looks like Simple Copper Pipes was missing a dependency and for some reason, updating this mod from .10 to .15 made this issue manifest despite Simple Copper Pipes working without its dependency (FrozenLib) up until now. Sorry for the noise!
