### ISSUE TITLE
Minecraft сrashes at startup. Lunar client.

### ISSUE THREAD

**Issue by k1llm3sixy** [wisp-forest/owo-lib#328]
Mc ver:1.20.1 fabric
Owo-lib ver:0.11.2

Crash log 

[3771e26d-dfe0-4646-b12b-a390e12de227-master.log](https://github.com/user-attachments/files/17611776/3771e26d-dfe0-4646-b12b-a390e12de227-master.log)

**Comment by Dragon-Seeker** [comment]
Honestly most likely a issue with lunar client and frankly multiple issues have occurred with it the point that I would think it best to say such breaks with owo, thoughts @gliscowo

**Comment by gliscowo** [comment]
Concurring with @Dragon-Seeker on this, we do not support Lunar Client
