### ISSUE TITLE
Handshake failure in single player. Nothing in the logs.

### ISSUE THREAD

**Issue by frikinjay** [wisp-forest/owo-lib#33]
I get this error and there is nothing to show for it in the logs. Only this screenshot. Using owo-lib-0.7.2-no-cme+1.18 with quilt 0.17.0

![image](https://user-images.githubusercontent.com/88995340/174248124-f89efb5d-3bca-400e-94aa-801c01c59b8d.png)

**Comment by gliscowo** [comment]
What specifically do you mean by "nothing in the logs"? A healthy install will show something along these lines
![image](https://user-images.githubusercontent.com/15788224/174304022-5e3f0b50-f130-42af-a605-bdbb9091522b.png)
Even in the case where handshaking completely fails, at least the server will still give log output regarding how and why it failed - if not, something is fundamentally broken. In any case, giving us your log will most likely aid in finding a solution
Cheers

**Comment by gliscowo** [comment]
Given that there has been no further activity on this issue, I will close it as stale
Cheers
