### ISSUE TITLE
STOP FUCKING WASTING MY TIME

### ISSUE THREAD

**Issue by ghost** [wisp-forest/owo-lib#335]
OH THIS SHITTY OWO-LIB NEEDS TO BE INSTALLED? OK ILL INSTALL IT. OH NOW FUCKING MINECRAFT DOESN'T OPEN CLEARLY THIS FUCKING MOD DOESN'T WORK LET ME REMOVE IT. OH OWO-LIB NEEDS TO BE INSTALLED

FIX YOUR FUCKING SHITTY ASS MOD

**Comment by chyzman** [comment]
no ❤️

**Comment by Dragon-Seeker** [comment]
@AutumnAgain I would like to state that to help with any debugging of owolib you need to send log information about the error or attempt to figure out the conflicting mod. I can understand that such can be frustrating but such is a part of modding Minecraft. Please drop the latest log and crash report combined with any other info to get help with the issue.

**Comment by ghost** [comment]
there is no log information minecraft just doesn't start when i have it installed

**Comment by chyzman** [comment]
if there's no log then you haven't started the game

**Comment by ghost** [comment]
ok this time it actually gave me a log, before it just didn't report anything, here you go

[00:07:03] [main/INFO]: Loading Minecraft 1.21.3 with Fabric Loader 0.16.9
[00:07:04] [main/INFO]: Loading 89 mods:
	- aether 1.5.1-beta.4
	   |-- accessories 1.1.0-beta.16+1.21.1
	   |    \-- owo-sentinel 0.12.15+1.21
	   |-- cumulus_menus 1.1.1
	   |    \-- mixinextras 0.5.0-beta.3
	   |-- mixinextras 0.5.0-beta.3
	   |-- mm_shedaniel 2.4.1
	   \-- nitrogen_internals 1.1.21
	- bettergrass 1.3.4+fabric.1.21.3
	- chat_heads 0.13.6
	- fabric-api 0.110.0+1.21.3
	   |-- fabric-api-base 0.4.50+119c825640
	   |-- fabric-api-lookup-api-v1 1.6.81+fd37071f40
	   |-- fabric-biome-api-v1 14.0.6+fd37071f40
	   |-- fabric-block-api-v1 1.0.28+fd37071f40
	   |-- fabric-block-view-api-v2 1.0.16+fd37071f40
	   |-- fabric-blockrenderlayer-v1 2.0.4+fd37071f40
	   |-- fabric-client-tags-api-v1 1.1.24+fd37071f40
	   |-- fabric-command-api-v1 1.2.58+f71b366f40
	   |-- fabric-command-api-v2 2.2.37+c9d82ab240
	   |-- fabric-commands-v0 0.2.75+df3654b340
	   |-- fabric-content-registries-v0 9.1.8+fd37071f40
	   |-- fabric-convention-tags-v1 2.1.3+7f945d5b40
	   |-- fabric-convention-tags-v2 2.9.3+84ebbb0e40
	   |-- fabric-crash-report-info-v1 0.3.3+fd37071f40
	   |-- fabric-data-attachment-api-v1 1.4.0+dbad41f140
	   |-- fabric-data-generation-api-v1 21.0.18+fd37071f40
	   |-- fabric-dimensions-v1 4.0.7+fd37071f40
	   |-- fabric-entity-events-v1 2.0.8+825023f840
	   |-- fabric-events-interaction-v0 2.0.12+c2c3ac4740
	   |-- fabric-game-rule-api-v1 1.0.59+fd37071f40
	   |-- fabric-item-api-v1 11.1.7+fd37071f40
	   |-- fabric-item-group-api-v1 4.1.17+fd37071f40
	   |-- fabric-key-binding-api-v1 1.0.53+fd37071f40
	   |-- fabric-keybindings-v0 0.2.51+df3654b340
	   |-- fabric-lifecycle-events-v1 2.5.1+6da5ef6940
	   |-- fabric-loot-api-v2 3.0.26+3f89f5a540
	   |-- fabric-loot-api-v3 1.0.14+fd37071f40
	   |-- fabric-message-api-v1 6.0.21+fd37071f40
	   |-- fabric-model-loading-api-v1 3.0.9+fd37071f40
	   |-- fabric-networking-api-v1 4.3.5+fd37071f40
	   |-- fabric-object-builder-api-v1 17.0.9+fd37071f40
	   |-- fabric-particles-v1 4.0.10+fd37071f40
	   |-- fabric-recipe-api-v1 7.0.4+fd37071f40
	   |-- fabric-registry-sync-v0 5.3.0+2758bfbf40
	   |-- fabric-renderer-api-v1 4.0.5+fd37071f40
	   |-- fabric-renderer-indigo 1.9.5+fd37071f40
	   |-- fabric-rendering-data-attachment-v1 0.3.54+73761d2e40
	   |-- fabric-rendering-fluids-v1 3.1.15+fd37071f40
	   |-- fabric-rendering-v0 1.1.84+df3654b340
	   |-- fabric-rendering-v1 8.0.8+6922831640
	   |-- fabric-resource-conditions-api-v1 5.0.8+fd37071f40
	   |-- fabric-resource-loader-v0 3.0.6+fd37071f40
	   |-- fabric-screen-api-v1 2.0.34+fd37071f40
	   |-- fabric-screen-handler-api-v1 1.3.101+fd37071f40
	   |-- fabric-sound-api-v1 1.0.29+fd37071f40
	   |-- fabric-transfer-api-v1 5.4.3+fd37071f40
	   \-- fabric-transitive-access-wideners-v1 6.2.0+54a41b1c40
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	- java 21
	- minecraft 1.21.3
	- modmenu 12.0.0-beta.1
	- placeholder-api 2.5.1+1.21.3
	- sodium 0.6.0+mc1.21.3
	- terralith 2.5.6
	- yet_another_config_lib_v3 3.6.1+1.21.2-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.14.2+1.21.3
	   \-- com_akuleshov7_ktoml-core-jvm 0.5.2
[00:07:07] [SwingWorker-pool-2-thread-1/INFO]: Fetching versions
[00:07:07] [SwingWorker-pool-2-thread-1/INFO]: Found matching version: 0.12.15+1.21
[00:07:07] [SwingWorker-pool-2-thread-1/INFO]: Downloading...
[00:07:07] [SwingWorker-pool-2-thread-1/INFO]: Success!

**Comment by Dragon-Seeker** [comment]
@AutumnAgain The aether and owolib will not work on 1.21.3 as they are for 1.21.1

**Comment by chyzman** [comment]
there's also a lot of log missing there

**Comment by ghost** [comment]
thats all the log reported before it just stopped

**Comment by Noaaan** [comment]
As mentioned: The Aether itself simply doesn't support 1.21.2+. You need to downgrade your Minecraft version and your mods should you wish to play it. 

![Screenshot_Aether_Modrinth](https://github.com/user-attachments/assets/a05680e6-f57a-4b5c-83a2-b106e9455c0c)

**Comment by uhloin** [comment]
Downgrade to "owo-lib-neoforge-0.12.15-beta.11+1.21.jar" 
Do not forget to remove invalid version(s) from mods folder.
