### ISSUE TITLE
Minecraft crashing error code 2

### ISSUE THREAD

**Issue by NikitaDarkstar** [wisp-forest/owo-lib#336]
The latest update causes Minecraft 1.21.1 (Neoforge) to crash, giving error code 2. Rolling back to the previous version fixes the problem.

**Comment by uhloin** [comment]
Yes log is here:

[stdout.txt](https://github.com/user-attachments/files/17958531/stdout.txt)

**Comment by Dragon-Seeker** [comment]
Ah my bad, I believe the latest was mis labeled for 1.21.1 instead of 1.21.3

**Comment by Dragon-Seeker** [comment]
Sorry about this as the script is currently set to 1.21.1 and forgot when uploading yesterday to adjust the version to 1.21.2 for latest release but it has been corrected now
