### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lowercasebtw** [wisp-forest/owo-lib#337]
https://mclo.gs/hwyR7cG

1.21.4, latest owo

Crash during game start

**Comment by Noaaan** [comment]
While owo shows up in this crash report, it seems that there were other mods that crashed way earlier  Notably it seems to be caused by `rlls` (not sure what mod this is)

**Comment by lowercasebtw** [comment]
Removed that mod as I know that one is incompatible forgot to remove it but I still get the OwO crash

**Comment by lowercasebtw** [comment]
nvm apparently there isn't a 1.21.4 version for owo-lib

**Comment by gliscowo** [comment]
Such a version has now [been released](https://github.com/wisp-forest/owo-lib/releases/tag/0.12.19%2B1.21.4)
Cheers
