### ISSUE TITLE
[owo-ui] Tooltips are not rendered when returning to a previously initialized screen

### ISSUE THREAD

**Issue by Zailer43** [wisp-forest/owo-lib#340]
## Description

I have:

```java
@Override
public void close() {
    this.setScreen(this.parent);
}
```
To return to the main screen but I’ve noticed that since version 0.12.19, tooltips are not rendered when returning to the previous screen

## Issue

This event should also be registered when the screen has been previously initialized
https://github.com/wisp-forest/owo-lib/blob/49a02fa04dab27ec82939bcfe66d5bbcdc30158b/src/main/java/io/wispforest/owo/ui/base/BaseOwoScreen.java#L96-L98
https://github.com/wisp-forest/owo-lib/blob/49a02fa04dab27ec82939bcfe66d5bbcdc30158b/src/main/java/io/wispforest/owo/ui/base/BaseOwoHandledScreen.java#L89-L91

## Versions

fabric_version = 0.111.0+1.21.4
owo_version = 0.12.19+1.21.4

**Comment by gliscowo** [comment]
@Dragon-Seeker
