### ISSUE TITLE
Possible crash with Terrablender

### ISSUE THREAD

**Issue by Sunconure11** [wisp-forest/owo-lib#40]
https://pastebin.com/PTbCiuUi

**Comment by Noaaan** [comment]
This seems to be caused by Charm. Could you try disabling it to see if the issue still occurs?

**Comment by Sunconure11** [comment]
Will test.

**Comment by Sunconure11** [comment]
https://pastebin.com/d9RN5MfH

https://pastebin.com/uMJb4EhE

It's never that simple.

**Comment by Noaaan** [comment]
Have you tried disabling owo?

**Comment by Sunconure11** [comment]
This issue was not from Owo lib
