### ISSUE TITLE
Owo lib kicks players out of the server before they can download a modpack.

### ISSUE THREAD

**Issue by KateReller** [wisp-forest/owo-lib#42]
I use [AutoModPack](https://github.com/Skidamek/AutoModpack) to have players download a modpack when they join, but it seems that owo lib kicks them out before they can download it.

`
[10:25:55 INFO] [Netty Epoll Server IO #0]: [owo] [Handshake] Handshake failed, client did not respond to channel query
[10:25:55 INFO] [Server thread]: [ServerLoginPacketListenerImpl] com.mojang.authlib.GameProfile@243c7a17[id=[id],name=[player],properties={textures=[com.mojang.authlib.properties.Property@38188169]},legacy=false] (/[ip]) lost connection: [oωo] handshake failure
incompatible client
`

**Comment by gliscowo** [comment]
[This section of the wiki](https://docs.wispforest.io/owo/system-properties/#-dowohandshakedisable-truefalse), which is conveniently linked in the readme by the way, explains how you can disable handshaking for such cases
Cheers

**Comment by oldjollysanta** [comment]
how/where do I change these settings? I'm so confused

**Comment by Noaaan** [comment]
I recommend reading this linked on the wiki page: https://stackoverflow.com/a/7054981

You add the setting to disable handshake to your servers launch args, which is added onto the same place where you chance ram settings

**Comment by oldjollysanta** [comment]
Thankyou! I understand now. I'm so sorry, I couldn't find any context from that wiki link (aka I'm blind). It seems so obvious now :S. Sorry for the waste of time, I really appreciate the assist!
