### ISSUE TITLE
[Suggestion] ARRP Support

### ISSUE THREAD

**Issue by ghost** [wisp-forest/owo-lib#45]
Would be amazing if all required block/item/etc. asset files (and also custom sprites from image files in the case of #44 being implemented) could be registered via [Advanced Runtime Resource Pack](https://www.curseforge.com/minecraft/mc-mods/arrp).

**Comment by gliscowo** [comment]
Could you join the [Discord](https://discord.gg/xrwHKktV2d) to discuss your suggestions further? All three of the issues you opened seem like something potentially worthy of being implemented, but I feel like some longer discussions about how to specially approach them might be in order.
Cheers

**Comment by gliscowo** [comment]
As discussed on Discord, this is best left to an addon mod and not going to be implemented in owo itself - thus I'm closing this issue
Cheers
