### ISSUE TITLE
Crashes on launch, on 1.19 with beta version 0.8+

### ISSUE THREAD

**Issue by TalEdd** [wisp-forest/owo-lib#50]
Only v0.7.3 works for 1.19. All the beta versions above it causes crash with maybe a incompatibility with Mythic Metal Decorations mod?

v0.8.0 crash: 
[crash-2022-09-11_15.16.41-client.txt](https://github.com/wisp-forest/owo-lib/files/9541974/crash-2022-09-11_15.16.41-client.txt)
[crash-2022-09-11_15.16.37-server.txt](https://github.com/wisp-forest/owo-lib/files/9541975/crash-2022-09-11_15.16.37-server.txt)

v0.8.3 crash:
[crash-2022-09-11_15.03.44-client.txt](https://github.com/wisp-forest/owo-lib/files/9541976/crash-2022-09-11_15.03.44-client.txt)
[crash-2022-09-11_15.03.40-server.txt](https://github.com/wisp-forest/owo-lib/files/9541977/crash-2022-09-11_15.03.40-server.txt)

**Comment by Noaaan** [comment]
This crash has already been fixed with the next version of Mythic Metals Decorations. it is not released yet, but It should be out in a day or so

**Comment by TalEdd** [comment]
Oh, I see. Thanks for the update!
