### ISSUE TITLE
Sentinel not working on MacOS

### ISSUE THREAD

**Issue by Noaaan** [wisp-forest/owo-lib#51]
See issue #50 for more context.

The latest version of owo-sentinel does not work on MacOS. 
Main problem right now is if it ever breaks in the future, we have currently no dedicated way of testing for all types of OS.

**Comment by gliscowo** [comment]
Fixed in [0.8.3](https://modrinth.com/mod/owo-lib/version/RV8F1iab)

**Comment by input-Here** [comment]
reporting on behalf of someone else, but this appears to still be an issue in owo-sentinel 0.8.5
(experienced on both quilt 0.19.2 and fabric 0.14.21)
