### ISSUE TITLE
owo-ui: .xsd schema outdated, missing dropdown documentation

### ISSUE THREAD

**Issue by Ratismal** [wisp-forest/owo-lib#53]
Hi,

I'm trying to create a UI using the dropdown component I found in source. However, this component is completely undocumented and missing from the schema file, so I'm running into issues figuring out how they actually work. I thought I'd drop an issue letting you know that it's missing from the schema.

Other issues I've found:
- Schema thinks that `collapsible` element cannot contain a `children` element

**Comment by gliscowo** [comment]
The dropdown component is now properly integrated in the schema, along with a few other fixes and corrections - thanks for bringing this up
Cheers
