### ISSUE TITLE
Wrong version published for 1.18, 0.7.2 instead of 0.7.3

### ISSUE THREAD

**Issue by FederAndInk** [wisp-forest/owo-lib#63]
In the changelogs it says 0.7.3 but its version 0.7.2, so you have 0.7.2 twice

https://www.curseforge.com/minecraft/mc-mods/owo-lib/files/3824297

![Screenshot_20221027_205325](https://user-images.githubusercontent.com/24270152/198374645-9d8e6528-f4a3-48a1-b09c-824bb2ccad04.png)

It's an issue for mods requiring version 0.7.3, as fabric throws an error

**Comment by Noaaan** [comment]
There is no official stable release of 0.7.3
The second 0.7.2 version is the `no-cme` build

**Comment by FederAndInk** [comment]
right, I was tricked by a fix of things+owo for 1.18.2. sorry. maybe the fix could be merged and published?
https://github.com/wisp-forest/things/pull/51
https://github.com/wisp-forest/owo-lib/pull/64
