### ISSUE TITLE
[Suggestion] owo-config: Support translating enums by overriding the toString() function

### ISSUE THREAD

**Issue by TacoMonkey11** [wisp-forest/owo-lib#65]
When switching from AutoConfig / Cloth Config to owo-config, I've noticed that the only way to translate enums is by adding the specific option and values to my translation file. For a single option and enum this is fine. But I have ton of options that use the same enum.

Now I have to copy and paste the same translations, just changing the option their for. With AutoConfig I could just override the toString() function in the enum which would set the translation. I'm not set on having it that way, but anything that reduces the translation file bloat would be nice.

**Comment by gliscowo** [comment]
Implemented in [0.9.0+1.19](https://modrinth.com/mod/owo-lib/version/lEVNuJ3B) with a new translation key format. Enums can now be translated on a per-config level with the `text.config.<config name>.enum.<enum name>.<value>` format
Cheers
