### ISSUE TITLE
[owo-config](Suggestion) Expand List when clicking "Add entry"

### ISSUE THREAD

**Issue by thimblebird** [wisp-forest/owo-lib#68]
right now, visually, nothing happens when clicking "Add entry" for a list. or at least one might not see something happened, adding 10 entries, maybe figuring out how to expand the list, then having to delete 9 entries again.

possibly, even focus the new entry so people can start typing instantly.

dat all 🐢

**Comment by gliscowo** [comment]
Implemented in [0.9.0+1.19](https://modrinth.com/mod/owo-lib/version/lEVNuJ3B)
