### ISSUE TITLE
[owo-config](Crash) Using `@PredicateConstraint` and clicking into a list

### ISSUE THREAD

**Issue by thimblebird** [wisp-forest/owo-lib#69]
using the [example for @PredicateConstraint](https://docs.wispforest.io/owo/config/constraints/#predicateconstraint) from the docs and then clicking into the list immediately crashes the game for me:

```
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to java.util.List
```

`owo_version = 0.8.5+1.19`
[latest.log](https://github.com/wisp-forest/owo-lib/files/9913076/latest.log)

**Comment by gliscowo** [comment]
Fixed in [0.9.0+1.19](https://modrinth.com/mod/owo-lib/version/lEVNuJ3B)
