### ISSUE TITLE
Can't join LAN world on a client without this mod

### ISSUE THREAD

**Issue by MightyKnight** [wisp-forest/owo-lib#72]
## Description
Creating a LAN world when owolib is installed prevents players without the library from joining, even though owolib (in my case) was only used for a client-only mod.
The mod I first noticed the issue with was [PocketWatch](https://modrinth.com/mod/pocketwatch), however I figured this was likely not an issue with PocketWatch, but rather with the library.
And indeed, even with owolib installed in isolation, it prevents players without it from joining.

## Reproduction steps
1. Install `owo-lib-0.8.5+1.19` and `quilted-fabric-api-4.0.0-beta.19+0.64.0-1.19.2` on a Quilt Loader 0.17.6 client
2. Create a world and share it to LAN with this _owolib client_
3. Launch another client, either vanilla or another modded on **without owolib**, and try to join the LAN world
:x: -> You will receive an error message

The following errors will be produced respectively:
- Trying to join with another quilt client with no owo-lib results in:
  ```
   Missing entries for registry "minecraft:sound_event":
   -  owo:ui.owo.interaction
   ``` 
- Trying to join with a vanilla client results in: **Unsupported (vanilla?) client.*

Hope I could provide all necessary information to help you debug the issue.

## Solution
Detect if a LAN world is running and not a normal server, and don't enable owolibs server features, but run it as if it was client only on the hosting client.

**Comment by gliscowo** [comment]
Fixed in [0.9.0+1.19](https://modrinth.com/mod/owo-lib/version/lEVNuJ3B)
