### ISSUE TITLE
Is there a way for @RangeConstraint to only show one decimal instead of 2?

### ISSUE THREAD

**Issue by TrevorSlobodnick** [wisp-forest/owo-lib#76]
currently I have the code:
```  
@RangeConstraint(min = 0.1, max = 100.0)
public double multiplier= 1.0;
```
This renders as a slider but the "step" value is 0.01 (2 decimal places) and I want to know if there's a way to set it to 0.1 (1 decimal place).

**Comment by gliscowo** [comment]
This is now available as a new property on the annotation in 0.10.0 and onwards
Cheers
