### ISSUE TITLE
Crashes When Custom player models is added

### ISSUE THREAD

**Issue by AshlyTheWolf** [wisp-forest/owo-lib#79]
When I add custom player models to my mods the game doesn't even boot to title for some reason and the errors say owo lib failed
[latest.log](https://github.com/wisp-forest/owo-lib/files/10333292/latest.log)

**Comment by Noaaan** [comment]
It seems like you are using the wrong version of owo-lib. You should be using the 0.9.3+1.19.3 version instead of 0.9.3+1.19

**Comment by AshlyTheWolf** [comment]
oh thanks that seem to fix it
