### ISSUE TITLE
[Suggestion] Make higher versions of content compatible with older versions

### ISSUE THREAD

**Issue by 70CentsApple** [wisp-forest/owo-lib#80]
I really love your 0.8.0 update, but unfortunately it seems to support only 1.19+ Minecraft versions. Please consider supporting these features for developers of 1.18.2 or below, especially annotations - that's my favorite feature.

**Comment by gliscowo** [comment]
While I understand that there might be plenty of valid reasons to be stuck developing on older versions, it it simply not feasible for us to keep backporting features and maintaining owo on multiple Minecraft versions. The differences between 1.19.3 and 1.18.2 are quite significant in a few places and 1.18.2 has now been past its support cycle for about half a year

Cheers
