### ISSUE TITLE
[owo-ui] memory leak on the screens delete

### ISSUE THREAD

**Issue by Zailer43** [wisp-forest/owo-lib#81]
Using spark I realized that the owo-lib screens instances are not deleted, in this spark I have opened and closed many times the owo-academy screen to end up with 36 instances in memory.

https://spark.lucko.me/N1DjtJCKWU
![image](https://user-images.githubusercontent.com/63565983/211055869-9c6156c0-e8a2-483a-9c2d-141db60dea36.png)

owo-lib version = owo-lib-0.9.3+1.19.3
owo-ui-academy version = https://github.com/wisp-forest/owo-ui-academy/actions/runs/3656591552
spark version = spark-1.10.17-fabric

**Comment by Zailer43** [comment]
in case anyone had a doubt if in the previous message I sent it before the garbage collector was executed, this `sparkclient heapsummary` is from a game of at least 6 hours.

https://spark.lucko.me/z5NKq5b6Nl
![image](https://user-images.githubusercontent.com/63565983/212527655-f9878483-ba61-4889-89c5-7377d3949606.png)

**Comment by BasiqueEvangelist** [comment]
This seems to be a Fabric API issue: it holds on to all screen events through a static field, that means that event handlers are kept, which means that screens are kept (through owo layers).
I'm going to make a PR that fixes this soon™
