### ISSUE TITLE
This library causes "names" to not render in world

### ISSUE THREAD

**Issue by Stelicx** [wisp-forest/owo-lib#84]
Basically when this library is in my mods folder, I can no longer see my animal's name, named items in item frames. I attached some screenshots to prove it. I'm playing Minecraft 1.19.3 and the mod version is 0.10.1. I spent atleast an hour to find the issue, when I finally found it there were only Fabric API and owo lib present in my mods folder. Some screenshots to better illustrate my issue.
1) https://prnt.sc/HW0vWZ-AE6KO
2) https://prnt.sc/az0mdlo55c_l

It's a real shame too, I was using it for the Fabric Waystones but I have to uninstall this lib as it is making me frustrated right now. Hope it is fixed in the future! I can provide any other additional help if needed.

**Comment by gliscowo** [comment]
Thanks for reporting, this is now fixed in [0.10.2](https://modrinth.com/mod/owo-lib/version/KMwbSA7v)
Cheers
