### ISSUE TITLE
When I use this mod I can't see names

### ISSUE THREAD

**Issue by SubwaySurfers69** [wisp-forest/owo-lib#90]
When I use this mod I can't see the names of any mobs with {CustomNameVisible:1b} and I can't find a config anywhere.
If this isn't an issue please help, I want to use a mod that requires this but I also want to be able to see names of entities.

**Comment by Noaaan** [comment]
This is potentially a duplicate of https://github.com/wisp-forest/owo-lib/issues/84, as it was fixed in owo-lib 0.10.2

**Comment by SubwaySurfers69** [comment]
ohh I'll install this manually because the mod was installing it and maybe it's not installing the latest version

**Comment by SubwaySurfers69** [comment]
I can see item frames though

**Comment by SubwaySurfers69** [comment]
Yep that worked thank you for helping Imma close this.
