### ISSUE TITLE
Edit as text tooltip renders on top of option tooltip

### ISSUE THREAD

**Issue by Awakened-Redstone** [wisp-forest/owo-lib#95]
The "Edit as text" and "Edit with slider" tooltip can render on top of the option tooptip (when present), making it unreadable and confusing

![image](https://user-images.githubusercontent.com/40528665/217335829-57b65f74-963f-4faa-ad88-90592b02df3b.png)

**Comment by gliscowo** [comment]
This has now been resolved as part of a larger overhaul to how components determine their hover states, released in [0.12.1](https://modrinth.com/mod/owo-lib/version/0.12.1+1.20.3)

Cheers
