### ISSUE TITLE
Broken font and config error

### ISSUE THREAD

**Issue by ghost** [wisp-forest/owo-lib#98]
When I launch minecraft with owo lib installed I got this error. But once I delete owo lib, mods required owo still working and there is no issue. In first seconds there is normal font, but then in turns into this and causing further issues. Like it don;'t let me change resourcepacks and crashing game.
![image](https://user-images.githubusercontent.com/124847943/220593617-0bcc8db2-8716-4cea-b78f-6c3788e5d0bf.png)

**Comment by gliscowo** [comment]
We need more information to properly investigate this, namely the list of mods you're using as well as their versions. Both of those pieces of information along with a lot of other useful data is available through the contents of the `latest.log` file right after this problem has occurred. Please attach it so we can look for solution

**Comment by ghost** [comment]
Ok, that's latest log with this issue: 
[latest.log](https://github.com/wisp-forest/owo-lib/files/10803927/latest.log)

**Comment by ghost** [comment]
I just had another crash when tried to join the world after pause in playing minecraft and got this short error report:
"The game crashed whilst rendering item
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null"

**Comment by ghost** [comment]
This issue self-fixed for unknown reasons. Can't replicate it again
